### ISSUE TITLE
nedes more engrok

### ISSUE THREAD

**Issue by v6** [bitcoin-studio/Bitcoin-VirtualMachine#1]
I did most of my work with 37coins SMS bitcoin wallet using Vagrant and ngrok, maybe 10 lines of code total to get a local Ubuntu with an introspective tunnel and a publicly accessible endpoint

Could throw letsencrypt on top of that but why guild the lily

**Comment by michaelfolkson** [comment]
Thanks @v6. Did you consider using ngrok @Janaka-Steph?

**Comment by v6** [comment]
Also I'm going to convert this to TF/Packr

**Comment by Janaka-Steph** [comment]
Ok, so I have no idea how to do that, but PR with a bit of documentation is welcome! 
For which use cases would you need something like that ?

**Comment by v6** [comment]
Any demos or tests of connections among nodes may benefit from this, as the API from within a Vagrant may be exposed publicly without going to the trouble of registering new DNS entries in the middle of, say, a hackathon.

**Comment by v6** [comment]
RiskBazaar used ngrok too, which was (I hope?) useful for comparing different app behavior without shoulder surfing or screenshare.
