### ISSUE TITLE
canonical Vagrant box

### ISSUE THREAD

**Issue by v6** [bitcoin-studio/Bitcoin-VirtualMachine#2]
Use app.vagrantup.com

e.g. https://app.vagrantup.com/bento/boxes/centos-7.5

**Comment by v6** [comment]
If you're worried about maintenance just do jenkins with git hooks and leave the packer code in there

**Comment by Janaka-Steph** [comment]
Sorry I am not a devops actually, I don't understand what is wrong. Can you explain a bit more?

**Comment by v6** [comment]
Packer's typical use case is for making "Vagrant Boxes", which are then used in a way similar to AMIs, by multiple different Vagrant projects. 

To allow public usage of the "Vagrant Box" made with the Packer configuration you've set up, here, you may register the Vagrant Box you produce at https://app.vagrantup.com

I highly recommend doing this, because it may be easier to discover on that platform.

**Comment by v6** [comment]
By the way, this is great work.

**Comment by Janaka-Steph** [comment]
Ok I will have a look on that. Thank you :-)

**Comment by Janaka-Steph** [comment]
@v6 Alright the box is now hosted on Vagrant Cloud! https://app.vagrantup.com/bitcoin-studio/boxes/Bitcoin-VirtualMachine  
Also I added the packer post-processor to update the box automatically. 
So I close the issue, reopen if there is an issue, I hope not! 
Thanks for the idea

**Comment by Janaka-Steph** [comment]
This vagrant-cloud post-processor seems actually very slow and shitty. See https://github.com/hashicorp/packer/issues/6615
I need to do more testing to see if I keep it.

**Comment by v6** [comment]
This is great. Now all I need to do when making a demo is this line of code: 

`vagrant init bitcoin-studio/Bitcoin-VirtualMachine; vagrant up; vagrant ssh`

**Comment by Janaka-Steph** [comment]
@v6 We still need to clone the repo and run vagrant commands inside the vagrant directory. It needs access to RSA keys and Ansible playbooks. But I am wondering if the box should not be already provisioned, if so the box is provisioned twice for nothing. I also need to check if we can get rid of RSA keys, I don't think it's really useful for this project.
